package fr.lteconsulting.hexa.client.comm;

public enum RPCErrorCodes
{
	ERROR_REQUEST_SEND,
	ERROR_REQUEST_RESPONSE_STATUS,
	ERROR_REQUEST_RESPONSE_EMPTY,
	ERROR_REQUEST_RESPONSE_PARSE,
	ERROR_REQUEST_GWT;
}
